### ISSUE TITLE
openssl mode: add capability to fine tune protocols, ciphers etc

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/librelp#116]
this should be done via a (set of) strings to be passed in (much like gnutls priority string).

**Comment by rgerhards** [comment]
@alorbach isn't that done?

**Comment by alorbach** [comment]
this is indeed implemented by commit: 
https://github.com/rsyslog/librelp/commit/1aa3f8c42f9cd99f4db45e107782b6718bf96ae3

The API's are:
- relpCltSetTlsConfigCmd
- relpSrvSetTlsConfigCmd

**Comment by alorbach** [comment]
already implemented, see https://github.com/rsyslog/librelp/issues/173
