### ISSUE TITLE
librelp 1.2.18 release not in git or tagged

### ISSUE THREAD

**Issue by andreasstieger** [rsyslog/librelp#128]
A librelp 1.2.18 release was [announced](https://www.adiscon.com/rsyslog/librelp-1-2-18-released/) is being distributed on http://rpms.adiscon.com/ with the following changelog:

```
Version 1.2.18 - 2018-09-18
- added non-standard "certvalid" auth mode to TLS authentication
- bugfix CI: make distcheck did not work
```

Please tag it in git.

**Comment by mbiebl** [comment]
I guess this bug report can be closed:
https://github.com/rsyslog/librelp/releases/tag/v.1.2.18
