### ISSUE TITLE
Multiple open commands during reconnects

### ISSUE THREAD

**Issue by perlei** [rsyslog/librelp#129]
Hi, 

Im using relp over a TCP proxy, and im getting problems duing reconnections attempts. 
The problem is that the TCP proxy first establishes the TCP connection, and when it 
realizes that the destination is not reachable it closes the connection. 

The problem is that relp send the "open" command every time the connection is made, and its
stored as a unacked message. So when the connection finally is established, the receiving 
relp-server will receive several "open" commands, and reply with a 500, and close the connection.
(this is using 1.2.17, its says 1.2.16, but im quite sure its 1.2.17). 

Below is the recording of a reconnected session. (syslogs removed) 

1 open 86 relp_version=0
relp_software=librelp,1.2.16,http://librelp.adiscon.com
commands=syslog
1 rsp 93 200 OK
2 syslog 363 SOME_SYSLOG_MSG
2 rsp 6 200 OK
3 open 86 relp_version=0
relp_software=librelp,1.2.16,http://librelp.adiscon.com
commands=syslog
4 open 86 relp_version=0
relp_software=librelp,1.2.16,http://librelp.adiscon.com
commands=syslog
5 open 86 relp_version=0
relp_software=librelp,1.2.16,http://librelp.adiscon.com
commands=syslog
6 open 86 relp_version=0
relp_software=librelp,1.2.16,http://librelp.adiscon.com
commands=syslog
7 open 86 relp_version=0
relp_software=librelp,1.2.16,http://librelp.adiscon.com
commands=syslog
8 open 86 relp_version=0
relp_software=librelp,1.2.16,http://librelp.adiscon.com
commands=syslog
9 syslog 363 SOME_SYSLOG_MSG
10 syslog 363 SOME_SYSLOG_MSG
11 syslog 365 SOME_SYSLOG_MSG
12 syslog 963 SOME_SYSLOG_MSG
3 rsp 27 500 connection already open
3 rsp 26 500 error 10047 on connect
0 serverclose 0

**Comment by rgerhards** [comment]
TBH I think the proxy is malfunctioning here. If it can't connect and signals "connection broken" to the peer, it needs to discard the message IMHO.

**Comment by perlei** [comment]
Well, you could argue that librelp only should send one "open" when a new tcp-connection is established. And not include the open from any previous connection. Since the relp-server is only expecting one.

**Comment by rgerhards** [comment]
maybe I don't understand your report. It sounds to me like the proxy buffers open commands. If librelp actually buffers the open commands, that would indeed be a librelp bug. librelp should discard the open if the connection fails.

If in doubt, can you post a network packet trace and a rsyslog debug log?

**Comment by perlei** [comment]
created with a bit older version, but behaviour is the same. 
[stripped.txt](https://github.com/rsyslog/librelp/files/2495795/stripped.txt)

**Comment by perlei** [comment]
As a quickfix could i comment out https://github.com/rsyslog/librelp/blob/master/src/copen.c#L136-L141 ? or will that have unknown consequences to allow multiple open on the server side?

**Comment by Kdecherf** [comment]
Hello,

I see the same issue with version `1.2.12-1+deb9u1`

**Comment by rgerhards** [comment]
sorry, many things in between...

> As a quickfix could i comment out https://github.com/rsyslog/librelp/blob/master/src/copen.c#L136-L141 ? or will that have unknown consequences to allow multiple open on the server side?

I would say it's not totally safe. But I hope to find the root cause now. It's unfortunately pretty hard to craft a test that creates this problem. I still try...

**Comment by rgerhards** [comment]
@perlei thx for the suggested patch. I have create a work-around based on it in #138. Please note that it is different from your original patch in that it terminates after sending the (fake) success response. This is required.

**Comment by perlei** [comment]
Awsome, thx for your efforts.

**Comment by perlei** [comment]
For reference I think logstash relp input has the same problem https://github.com/logstash-plugins/logstash-input-relp/issues/22 so i guess a similar fix should be done by them, to allow multiple open throughout the session.

**Comment by rgerhards** [comment]
@perlei sorry, the server-side patch does not work. Unfortunately, there is no server-side workaround: whatever we do, small changes need to be made to the client code as well. PR #141 now fixes this on the client side (hopefully this time really, as tests are still under development). That should solve all issues, also with the logstash receiver. The problem actually is client-side only. I just tried to avoid the need to update each client, but it's not possible.
