### ISSUE TITLE
No way to shutdown gracefully server without connected client

### ISSUE THREAD

**Issue by serathius** [rsyslog/librelp#16]
Setting stop only works when server is connected to client. 
In case when I want to replace server by load balancing and redirecting logs to new server instance, old server is left without connected client. In that case only way to stop server is SIGKILL or connecting fake client.

Similarly there is no way of turning off server, that never had any client connected to it.

**Comment by rgerhards** [comment]
@alorbach can you check - I think this was fixed

**Comment by alorbach** [comment]
I think this issue is most likely already be fixed.

**Comment by rgerhards** [comment]
I am closing this for now. If somebody experiences this with new versions, please open a new issue tracker.
