### ISSUE TITLE
openssl

### ISSUE THREAD

**Issue by gitus** [rsyslog/librelp#169]
Hi,

I have same issue as : https://github.com/rsyslog/rsyslog/issues/2541

I am using omrelp on CentOS6 and it needs rsyslog-gnutls so i tried building librelp with openssl and without gnutls and I got the error below, is it normal ?

> $ ./configure --enable-tls-openssl
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
HOST:
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... none needed
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
configure: WARNING: missing AX_IS_RELEASE macro, not using AX_COMPILER_FLAGS macro because of this
checking for library containing clock_gettime... none required
checking for ANSI C header files... (cached) yes
checking sys/epoll.h usability... yes
checking sys/epoll.h presence... yes
checking for sys/epoll.h... yes
checking for an ANSI C-conforming const... yes
checking for size_t... yes
checking for struct sockaddr.sa_len... no
checking sys/select.h usability... yes
checking sys/select.h presence... yes
checking for sys/select.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking types of arguments for select... int,fd_set *,struct timeval *
checking whether strerror_r is declared... yes
checking for strerror_r... yes
checking whether strerror_r returns char *... no
checking return type of signal handlers... void
checking for strerror_r... (cached) yes
checking for strdup... yes
checking for epoll_create... yes
checking for epoll_create1... yes
checking for OPENSSL... yes
checking for GNUTLS... no
configure: error: Package requirements (gnutls >= 2.0.0) were not met:
No package 'gnutls' found
Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.
Alternatively, you may set the environment variables GNUTLS_CFLAGS
and GNUTLS_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

**Comment by rgerhards** [comment]
You do not have the development dependencies installed. I think gnutls-devel is missing here. But I would recommend that you use the prebuild packages we provide for CentOS 6,

**Comment by gitus** [comment]
the main goal here is to build librelp with openssl and not gnutls. Is it possible ?

**Comment by rgerhards** [comment]
> the main goal here is to build librelp with openssl and not gnutls. Is it possible ?

of course, just specify the proper configure option. I guess it is `--enable-tls-openssl`. But if you are not used to build things yourself, you are probably better of with the prebuild packages.

**Comment by gitus** [comment]
--enable-tls-openssl is the argument I used (cf my first post)
why am I required to install gnutls although i want to use openssl ?

**Comment by rgerhards** [comment]
read `./configure.sh --help`

**Comment by gitus** [comment]
it says : 
  --enable-tls            Enable TLS support [default=no]
  --enable-tls-openssl    Enable OpenSSL TLS support [default=yes]

Does that mean that gnutls is necessary even if I use openssl ?

I would be glad to use the prebuild package but it is the one which causes the bug in the first place.

**Comment by rgerhards** [comment]
aha! text on the default is wrong. Both tls libs are enabled by default. So you need to use `--disable-tls` to disable gnutls (historic name).

**Comment by rgerhards** [comment]
> I would be glad to use the prebuild package but it is the one which causes the bug in the first place.

I just realized this: the prebuild package supports both gnutls and openssl. You can configure which one to use via rsyslog config.

**Comment by gitus** [comment]
Thank you, I can now build the library.

> I just realized this: the prebuild package supports both gnutls and openssl. You can configure which one to use via rsyslog config.

I checked [https://www.rsyslog.com/doc/v8-stable/configuration/modules/omrelp.html?highlight=relp#tls-prioritystring](https://www.rsyslog.com/doc/v8-stable/configuration/modules/omrelp.html?highlight=relp#tls-prioritystring)

There is no mention of openssl, how can I choose it over gnutls with the prebuild package ?

**Comment by rgerhards** [comment]
> There is no mention of openssl, how can I choose it over gnutls with the prebuild package ?

oh - this looks like the doc auto-update seems to be stalled. In short
```
module(load="imrelp" tls.tlslib="openssl")
```

**Comment by gitus** [comment]
It works!

Thank you for your help.

**Comment by rgerhards** [comment]
glad to hear all is well!
