### ISSUE TITLE
Duplicate logs when using RELP over TLS after connexion breakage

### ISSUE THREAD

**Issue by dud225** [rsyslog/librelp#56]
Hello

I've observed duplicate logs when using RELP on top of TLS connection whenever there is a connection breaks. This behaviour doesn't happen on non-TLS setup.

RELP client displays from times to times messages related to GnuTLS : 
```
ibrelp: gnutls_record_recv must be retried
relpSessWaitState returns 0
frame to send: '3 syslog 118 <141>1 2017-01-13T18:11:47.589943+01:00 ...
'
ibrelp: TLS send returned 132
ADD sess 0x7f5120002440 unacked 2, sessState 4
sendbuf added to unacked list
shutdownImmediate ptr now is 0x7f512ef4fa18
[...]
librelp: gnutls_record_recv must be retried
relpSessWaitState returns 0
frame to send: '32 syslog 118 <141>1 2017-01-13T18:11:47.589943+01:00 ....
'
librelp: TLS send returned 133
ADD sess 0x7f5120002440 unacked 31, sessState 4
sendbuf added to unacked list
omrelp: shutdownImmediate ptr now is 0x7f512ef4fa18
```
The message is received by the serveur though.

After a connection breakage (server restart in my case), I see 
```
end relpSessConnect, iRet 0
relp session 0x7f5120002440 reestablished, now resending 31 unacked frames
```

and then some messages are written twice on server side.

**Comment by rgerhards** [comment]
RELP guards against message loss, but it does so at the expense of some potential message duplication.
