### ISSUE TITLE
Make gnutls mandatory/remove --{enable,disable}-tls from configure

### ISSUE THREAD

**Issue by dev-zero** [rsyslog/librelp#6]
`src/tcp.h` always requires gnutls, so librelp can not be built without it anymore as it seems.
Therefore the check in `configure.ac` is wrong.

**Comment by Whissi** [comment]
This is now fixed in v1.2.9 with commit 517501bd7650f4.

**Comment by abiacco** [comment]
This fix is much appreciated. Thank you.
